### ISSUE TITLE
Levenshtein TypeError in python 3.8

### ISSUE THREAD

**Issue by ThomasMAhern** [abstractqqq/polars_ds_extension#68] opened 2024-02-06 08:31 UTC
I get a `TypeError: 'type' object is not subscriptable` in python 3.8 when I use Levenshtein distance that I don't get in python 3.10
```python
(pl.from_dict({'a': 'test', 'b': 'toast'})
  .with_columns(l_dist = pl.col('a').str2.levenshtein(pl.col('b'))))

**Comment by abstractqqq** [comment] 2024-02-06 14:18
Can you check version when running the package in 3.8? Try pip list when in the 3.8 env. I believe it is because you are running old code from a while ago. I remember changing requirements to Python >= 3.9 a while ago.

**Comment by abstractqqq** [comment] 2024-02-06 14:21
That said, maybe I should look into the issue with 3.8 more instead of just asking for higher version of Python...

**Comment by ThomasMAhern** [comment] 2024-02-06 14:51
Ah, that's fair, the env I'm working is unfortunately 3.8. Didn't even think to check on minimum version. 
Would it be something `from __future__ import annotations` could help with? (I just ran into a similar problem on another project - this was the solution)

**Comment by abstractqqq** [comment] 2024-02-06 21:36
I believe the issue is fixed, the package is able to build with Python 3.8 and all tests have passed, and this will be in the next release (v.0.3.1) coming this weekend. 

It is a rather silly issue with typing in Python 3.8 that I had trouble with lol.

https://github.com/abstractqqq/polars_ds_extension/commit/82f2760c02d566a0631451d1f99fe7d548db681d

**Closed by abstractqqq** 2024-02-06 21:36 UTC
Labels: good first issue

**Comment by abstractqqq** [comment] 2024-02-09 18:30
Just relaeased v0.3.1. You can try later today or this weekend. Please let me know!
